
[functions.sync-ratings]
enabled = true
verify_jwt = true
import_map = "./functions/sync-ratings/deno.json"
entrypoint = "./functions/sync-ratings/index.ts"

[functions.sync-scheduler]
enabled = true
verify_jwt = true
import_map = "./functions/sync-scheduler/deno.json"
entrypoint = "./functions/sync-scheduler/index.ts"
schedule = "0 0 * * *"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/sync-ratings/*.html" ]
