[functions.cron-livescores]
enabled = true
verify_jwt = true
import_map = "./functions/cron-livescores/deno.json"
entrypoint = "./functions/cron-livescores/index.ts"

[functions.cron-purge-notifications]
enabled = true
verify_jwt = true
import_map = "./functions/cron-purge-notifications/deno.json"
entrypoint = "./functions/cron-purge-notifications/index.ts"
